---
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:17"
      timezone: "Etc/UTC"
    commit-message:
      prefix: "build(NoTicket)"
    open-pull-requests-limit: 20
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:30"
      timezone: "Etc/UTC"
    commit-message:
      prefix: "build(NoTicket)"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "logback-classic"
        # logback-classic 1.4 requires java 11+
        versions: ["1.4.x"]
        # Mockito 5 requires java 11+
      - dependency-name: "mockito-inline"
        versions: ["5.x.x"]
      - dependency-name: "mockito-junit-jupiter"
        versions: ["5.x.x"]
      - dependency-name: "mockito-core"
        versions: ["5.x.x"]
        # Pioneer 2 requires java 11+
      - dependency-name: "junit-pioneer"
        versions: ["2.x.x"]
    groups:
      gradle:
        patterns:
          - "*"
