package com.firebolt.jdbc.metadata;

import lombok.experimental.UtilityClass;

/**
 * Column names to include in the {@link java.sql.ResultSet} as specified in the
 * {@link java.sql.DatabaseMetaData} javadoc
 */
@UtilityClass
public class MetadataColumns {
	public static final String TABLE_CAT = "TABLE_CAT";
	public static final String TABLE_CATALOG = "TABLE_CATALOG";
	public static final String TABLE_SCHEM = "TABLE_SCHEM";
	public static final String TABLE_NAME = "TABLE_NAME";
	public static final String COLUMN_NAME = "COLUMN_NAME";
	public static final String DATA_TYPE = "DATA_TYPE";
	public static final String TYPE_NAME = "TYPE_NAME";
	public static final String COLUMN_SIZE = "COLUMN_SIZE";
	public static final String BUFFER_LENGTH = "BUFFER_LENGTH";
	public static final String DECIMAL_DIGITS = "DECIMAL_DIGITS";
	public static final String NULLABLE = "NULLABLE";
	public static final String REMARKS = "REMARKS";
	public static final String COLUMN_DEF = "COLUMN_DEF";
	public static final String COLUMN_USAGE = "COLUMN_USAGE";
	public static final String CHAR_OCTET_LENGTH = "CHAR_OCTET_LENGTH";
	public static final String ORDINAL_POSITION = "ORDINAL_POSITION";
	public static final String IS_NULLABLE = "IS_NULLABLE";
	public static final String SCOPE_CATALOG = "SCOPE_CATALOG";
	public static final String SCOPE_SCHEMA = "SCOPE_SCHEMA";
	public static final String SCOPE_TABLE = "SCOPE_TABLE";
	public static final String SOURCE_DATA_TYPE = "SOURCE_DATA_TYPE";
	public static final String IS_AUTOINCREMENT = "IS_AUTOINCREMENT";
	public static final String IS_GENERATEDCOLUMN = "IS_GENERATEDCOLUMN";
	public static final String TABLE_TYPE = "TABLE_TYPE";
	public static final String TYPE_CAT = "TYPE_CAT";
	public static final String TYPE_SCHEM = "TYPE_SCHEM";
	public static final String SELF_REFERENCING_COL_NAME = "SELF_REFERENCING_COL_NAME";
	public static final String REF_GENERATION = "REF_GENERATION";
	public static final int COMMON_RADIX = 10;
	public static final String PRECISION = "PRECISION";
	public static final String LITERAL_PREFIX = "LITERAL_PREFIX";
	public static final String LITERAL_SUFFIX = "LITERAL_SUFFIX";
	public static final String CREATE_PARAMS = "CREATE_PARAMS";
	public static final String CASE_SENSITIVE = "CASE_SENSITIVE";
	public static final String SEARCHABLE = "SEARCHABLE";
	public static final String UNSIGNED_ATTRIBUTE = "UNSIGNED_ATTRIBUTE";
	public static final String FIXED_PREC_SCALE = "FIXED_PREC_SCALE";
	public static final String AUTO_INCREMENT = "AUTO_INCREMENT";
	public static final String LOCAL_TYPE_NAME = "LOCAL_TYPE_NAME";
	public static final String MINIMUM_SCALE = "MINIMUM_SCALE";
	public static final String MAXIMUM_SCALE = "MAXIMUM_SCALE";
	public static final String SQL_DATA_TYPE = "SQL_DATA_TYPE";
	public static final String SQL_DATETIME_SUB = "SQL_DATETIME_SUB";
	public static final String NUM_PREC_RADIX = "NUM_PREC_RADIX";
	public static final String FUNCTION_CAT = "FUNCTION_CAT";
	public static final String FUNCTION_SCHEM = "FUNCTION_SCHEM";
	public static final String FUNCTION_NAME = "FUNCTION_NAME";
	public static final String FUNCTION_TYPE = "FUNCTION_TYPE";
	public static final String SPECIFIC_NAME = "SPECIFIC_NAME";
	public static final String COLUMN_TYPE = "COLUMN_TYPE";
	public static final String LENGTH = "LENGTH";
	public static final String SCALE = "SCALE";
	public static final String RADIX = "RADIX";
	public static final String KEY_SEQ = "KEY_SEQ";
	public static final String PSEUDO_COLUMN = "PSEUDO_COLUMN";
	public static final String SCOPE = "SCOPE";
	public static final String PROCEDURE_CAT = "PROCEDURE_CAT";
	public static final String PROCEDURE_SCHEM = "PROCEDURE_SCHEM";
	public static final String PROCEDURE_NAME = "PROCEDURE_NAME";
	public static final String PROCEDURE_TYPE = "PROCEDURE_TYPE";
	public static final String SUPERTABLE_NAME = "TABLE_NAME";
	public static final String SUPERTYPE_NAME = "SUPERTYPE_NAME";
	public static final String SUPERTYPE_CAT = "SUPERTYPE_CAT";
	public static final String SUPERTYPE_SCHEM = "SUPERTYPE_SCHEM";
	public static final String CLASS_NAME = "CLASS_NAME";
	public static final String BASE_TYPE = "BASE_TYPE";
	public static final String ATTR_NAME = "ATTR_NAME";
	public static final String ATTR_TYPE_NAME = "ATTR_TYPE_NAME";
	public static final String ATTR_SIZE = "ATTR_SIZE";
	public static final String ATTR_DEF = "ATTR_DEF";
	public static final String NAME = "NAME";
	public static final String MAX_LEN = "MAX_LEN";
	public static final String DEFAULT_VALUE = "DEFAULT_VALUE";
	public static final String DESCRIPTION = "DESCRIPTION";
	public static final String PKTABLE_CAT = "PKTABLE_CAT";
	public static final String PKTABLE_SCHEM = "PKTABLE_SCHEM";
	public static final String PKTABLE_NAME = "PKTABLE_NAME";
	public static final String PKCOLUMN_NAME = "PKCOLUMN_NAME";
	public static final String FKTABLE_CAT = "FKTABLE_CAT";
	public static final String FKTABLE_SCHEM = "FKTABLE_SCHEM";
	public static final String FKTABLE_NAME = "FKTABLE_NAME";
	public static final String FKCOLUMN_NAME = "FKCOLUMN_NAME";
	public static final String UPDATE_RULE = "UPDATE_RULE";
	public static final String DELETE_RULE = "DELETE_RULE";
	public static final String FK_NAME = "FK_NAME";
	public static final String PK_NAME = "PK_NAME";
	public static final String DEFERRABILITY = "DEFERRABILITY";
	public static final String GRANTOR = "GRANTOR";
	public static final String GRANTEE = "GRANTEE";
	public static final String PRIVILEGE = "PRIVILEGE";
	public static final String IS_GRANTABLE = "IS_GRANTABLE";
	public static final String NON_UNIQUE = "NON_UNIQUE";
	public static final String INDEX_QUALIFIER = "INDEX_QUALIFIER";
	public static final String INDEX_NAME = "INDEX_NAME";
	public static final String TYPE = "TYPE";
	public static final String ASC_OR_DESC = "ASC_OR_DESC";
	public static final String CARDINALITY = "CARDINALITY";
	public static final String PAGES = "PAGES";
	public static final String FILTER_CONDITION = "FILTER_CONDITION";
}
