name: Core integration tests

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'The docker image tag for the firebolt core'
        required: false
        type: string
      java_version:
        description: 'JRE version'
        required: false
        type: string
        default: '11'
      os_name:
        description: 'The operating system'
        required: false
        type: string
        default: 'ubuntu-latest'
      sendSlackNotifications:
        description: 'Send Slack notifications on failure'
        required: false
        type: boolean
        default: false
  workflow_call:
    inputs:
      tag_version:
        description: 'The docker image tag for the firebolt core'
        required: false
        type: string
      java_version:
        description: 'Java'
        required: false
        type: string
        default: '11'
      os_name:
        description: 'Operating system'
        required: false
        type: string
        default: 'ubuntu-latest'
      sendSlackNotifications:
        description: 'Send Slack notifications on failure'
        required: false
        type: boolean
        default: false
    secrets:
      SLACK_BOT_TOKEN:
        required: false
jobs:
  run-core-integration-tests:
    runs-on: ${{ inputs.os_name }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ inputs.java_version }}
          cache: 'gradle'

      - name: Setup Firebolt Core
        id: setup-core
        uses: firebolt-db/action-setup-core@fix-java-keystore
        with:
          tag_version: ${{ inputs.tag_version || vars.DEFAULT_CORE_IMAGE_TAG }}

      - name: Grant execute permission (Unix)
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Run integration tests
        run: ./gradlew integrationTest -DincludeTags="core" -Ddb=integration_test_db --info
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false

      - name: Slack Notify of failure
        if: failure() && inputs.sendSlackNotifications
        uses: firebolt-db/action-slack-nightly-notify@v1
        with:
          os: ${{ inputs.os_name }}
          programming-language: Java
          language-version: ${{ inputs.java_version }}
          notifications-channel: 'ecosystem-ci-notifications'
          slack-api-key: ${{ secrets.SLACK_BOT_TOKEN }}
