name: Nightly integration tests core

on:
  schedule:
    - cron: '30 0 * * *'        # Daily at 03:00 UTC
  workflow_dispatch:             # Allow manual trigger

jobs:
  detect-latest-images-available:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: detect latest images available
        id: set-matrix
        env:
          PREFIXES: ${{ vars.CORE_IMAGE_PREFIXES }}
          SUFFIX: "amd64"
        run: |
          echo "Querying GHCR image tags from firebolt-db/firebolt-core..."
          
          # Query image versions from GitHub Container Registry
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/orgs/firebolt-db/packages/container/firebolt-core/versions?per_page=100")
          
          # Check if response is empty or null
          if [ -z "$response" ]; then
            echo "Error: Empty response from API"
            exit 1
          fi
          
          # Convert PREFIXES from JSON array to bash array
          prefixes=($(echo $PREFIXES | jq -r '.[]'))
          
          # Initialize matrix array
          matrix="["
          first=true
          
          # For each prefix, find the latest tag
          for prefix in "${prefixes[@]}"; do
            echo "Looking for tags with prefix: ${prefix} and suffix: ${SUFFIX}"
            
            LATEST_TAG=$(echo "$response" | jq -r --arg prefix "$prefix" --arg suffix "$SUFFIX" '
              if . == null then
                error("Response is null")
              else
                .[] | 
                if .metadata == null then
                  empty
                elif .metadata.container == null then
                  empty
                elif .metadata.container.tags == null then
                  empty
                else
                  . as $parent |
                  .metadata.container.tags[] | 
                  select(. != null) |
                  select(startswith($prefix) and endswith($suffix)) |
                  {tag: ., created: $parent.created_at} |
                  "\(.created) \(.tag)"
                end
              end
            ' | sort -r | head -n 1 | awk '{print $2}')
            
            if [ -z "$LATEST_TAG" ]; then
              echo "Warning: No matching tags found with prefix ${prefix} and suffix ${SUFFIX}"
              continue
            fi
            
            echo "Latest matching tag for ${prefix}: $LATEST_TAG"
            
            # Add to matrix
            if [ "$first" = true ]; then
              first=false
            else
              matrix+=","
            fi
            matrix+="{\"tag\":\"$LATEST_TAG\"}"
          done
          
          matrix+="]"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  nightly-integration-runs-core:
    needs: detect-latest-images-available
    strategy:
      matrix:
        image: ${{ fromJson(needs.detect-latest-images-available.outputs.matrix) }}
    uses: ./.github/workflows/core-integration-test.yml
    with:
      os_name: ubuntu-latest
      java_version: 11
      tag_version: ${{ matrix.image.tag }}
      sendSlackNotifications: true
    secrets: inherit
