name: Nightly integration tests core

on:
  schedule:
    - cron: '30 0 * * *'        # Daily at 03:00 UTC
  workflow_dispatch:             # Allow manual trigger

jobs:
  detect-latest-image-available:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: detect latest image availabe
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PREFIX: "4.21"
          SUFFIX: "x86"
        run: |
          echo "Querying GHCR image tags from $OWNER/$IMAGE_NAME..."
          
          # Query image versions from GitHub Container Registry
          response=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
            "https://api.github.com/users/firebolt-db/firebolt-core/packages/container/firebolt-core/versions?per_page=100")
          
          echo "$response" | jq -r '
            .[]
            | select(.metadata.container.tags != null and (.metadata.container.tags | length > 0))
            | {tag: .metadata.container.tags[0], created: .created_at}
            | @base64
          ' | while read -r entry; do
            _jq() {
              echo "$entry" | base64 --decode | jq -r "$1"
            }
      
          tag=$(_jq '.tag')
          created=$(_jq '.created')
          
          if [[ "$tag" == ${PREFIX}*${SUFFIX} ]]; then
          echo "$created $tag"
          fi
          done | sort -r | head -n 1 | awk '{ print "latest_tag=" $2 }' >> "$GITHUB_OUTPUT"

  nightly-integration-runs-core:
    needs: detect-latest-image-available
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/core-integration-test.yml
        with:
          os_name: ubuntu-latest
          java_version: 11
          tag_version: ${{ needs.detect-latest-image-available.outputs.latest_tag }}
