name: Nightly integration tests core

on:
  schedule:
    - cron: '30 0 * * *'        # Daily at 03:00 UTC
  workflow_dispatch:             # Allow manual trigger

jobs:
  nightly-integration-runs-core:
    uses: ./.github/workflows/core-integration-test.yml
    with:
      os_name: ubuntu-latest
      java_version: 11
      tag_version: ${{ vars.CORE_NIGHTLY_IMAGE_TAG }}
      sendSlackNotifications: true
    secrets: inherit
