name: Pre-release test

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: ./github/workflows/build.yml

#  run-integration-test:
#    needs: build
#    uses: ./.github/workflows/integration-test.yml

  run-smoke-test:
    needs: run-integration-test
    uses: ./github/workflows/sandbox-smoke-test.yaml
    with:
      jdbcJar: ${{ needs.build.outputs.uber-jar }}
      runId: 1234
