name: Pre-release test

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      FIREBOLT_STG_USERNAME:
        required: true
      FIREBOLT_STG_PASSWORD:
        required: true
      FIREBOLT_CLIENT_ID_STG_NEW_IDN:
        required: true
      FIREBOLT_CLIENT_SECRET_STG_NEW_IDN:
        required: true
      FIREBOLT_CORE_DEV_CERT_PRIVATE_KEY:
        required: true
      FIREBOLT_CORE_DEV_CERT:
        required: true
jobs:
  build:
    uses: ./.github/workflows/build.yml

  run-cloud-integration-test:
    needs: build
    uses: ./.github/workflows/integration-test.yml
    secrets: inherit

  run-core-integration-tests:
    needs: build
    uses: ./.github/workflows/core-integration-test.yml
    secrets: inherit

  run-smoke-test:
    needs: build
    uses: ./.github/workflows/sandbox-smoke-test.yml
    with:
      jdbcJar: ${{ needs.build.outputs.uber-jar }}
      runId: ${{ github.run_id }}
