name: Pull request

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
  code-coverage:
    uses: ./.github/workflows/code-coverage.yml
